apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: openebs-std-0.5.2
provisioner: openebs.io/provisioner-iscsi
parameters:
  openebs.io/storage-pool: "default"
  openebs.io/jiva-replica-count: "1"
  openebs.io/volume-monitor: "true"
  openebs.io/capacity: 2G
---
apiVersion: openebs.io/v1alpha1
kind: StoragePool
metadata:
  name: ssd
  type: hostdir
spec:
  path: "/var/myebs"
---
apiVersion: openebs.io/v1alpha1
kind: StoragePool
metadata:
  name: default
  type: hostdir
spec:
  path: "/var/mydefault"
