# openebs service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openebs-operator
  namespace: openebs
---
# ClusterRole since openebs operations are cluster wide
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: openebs-operator
rules:
- apiGroups: ["*"]
  resources: ["nodes","nodes/proxy"]
  verbs: ["get","list","watch","create","update"]
- apiGroups: ["*"]
  resources: ["namespaces","services","pods","deployments", "events", "endpoints"]
  verbs: ["*"]
- apiGroups: ["*"]
  resources: ["persistentvolumes","persistentvolumeclaims"]
  verbs: ["*"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["*"]
- apiGroups: ["*"]
  resources: ["storagepools"]
  verbs: ["get", "list"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
# ClusterRoleBinding binds openebs service account with the ClusterRole 
# privileges.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: openebs-operator
subjects:
- kind: ServiceAccount
  name: openebs-operator
  namespace: openebs
roleRef:
  kind: ClusterRole
  name: openebs-operator
  apiGroup: rbac.authorization.k8s.io
