{{- if .Values.policies.monitoring.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: openebs-prometheus-tunables
{{- if .Values.rbacEnable }}
  namespace: {{ .Values.rbac.namespace }}
{{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  storage-retention: 24h
{{- end }}
