apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: maya-apiserver
{{- if .Values.rbacEnable }}
  namespace: {{ .Values.rbac.namespace }}
{{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: maya-apiserver
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    spec:
      serviceAccountName: {{ .Values.operator.name }}
      containers:
      - name: maya-apiserver
        image: "{{ .Values.apiserver.image }}:{{ .Values.apiserver.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports: 
        - containerPort: 5656
        env:
        # OPENEBS_IO_KUBE_CONFIG enables maya api service to connect to K8s
        # based on this config. This is ignored if empty.
        # This is supported for maya api server version 0.5.2 onwards
        #- name: OPENEBS_IO_KUBE_CONFIG
        #  value: "/home/ubuntu/.kube/config"
        # OPENEBS_IO_K8S_MASTER enables maya api service to connect to K8s
        # based on this address. This is ignored if empty.
        # This is supported for maya api server version 0.5.2 onwards
        #- name: OPENEBS_IO_K8S_MASTER
        #  value: "http://172.28.128.3:8080"
        - name: OPENEBS_IO_JIVA_CONTROLLER_IMAGE
          value: {{ .Values.jiva.image }}
        - name: OPENEBS_IO_JIVA_REPLICA_IMAGE
          value: {{ .Values.jiva.image }}
        - name: OPENEBS_IO_VOLUME_MONITOR_IMAGE
          value: "{{ .Values.policies.monitoring.image }}"
        - name: OPENEBS_IO_JIVA_REPLICA_COUNT
          value: "{{ .Values.jiva.replicas }}"
